ignite: {
  network: {
    # GridGain 9 node port
    port = 3344
    nodeFinder = {
      netClusterNodes = [
        # Kubernetes service to access the GridGain 9 cluster on the Kubernetes network
        "gridgain-svc-headless:3344"
      ]
    }
  }

  storage: {
    profiles = [
      {
        engine = "aipersist"
        name = "default"
        replacementMode = "CLOCK"
        # Explicit storage size configuration
        sizeBytes = 2147483648
      }
    ]
  }
}