apiVersion: v1
kind: Service
metadata:
  name: gridgain-loadbalancer
  labels:
    app: gridgain
  namespace: ignite
spec:
  type: LoadBalancer
  selector:
    app: gridgain
  ports:
    - name: rest
      protocol: TCP
      port: 10800
      targetPort: 10800
    - name: client
      port: 10300
      protocol: TCP
      targetPort: 10300