apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ignite
spec:
  replicas: 2
  serviceName: "ignite"
  selector:
    matchLabels:
      app: ignite
  # this is the default, but no harm in being explict
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ignite
        type: server
    spec:
      volumes:
        - name: ignite-config
          configMap:
            name: ignite-config
            items:
            - key: ignite-config.xml
              path: ignite-config.xml
        - name: ignite-licence
          configMap:
            name: ignite-licence
            items:
            - key: gridgain-license.xml
              path: gridgain-license.xml
      terminationGracePeriodSeconds: 60000
      containers:
      - name: ignite-node
        image: gridgain/ultimate:8.8.30-openjdk17-slim
        resources:
          limits:
            memory: 1536Mi
            cpu: 1
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        env:
        - name: IGNITE_QUIET
          value: "false"
        - name: JVM_OPTS
          value: -server -Djava.net.preferIPv4Stack=true -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -Djdk.tls.client.protocols=TLSv1.2
        - name: OPTION_LIBS
          value: ignite-kubernetes,ignite-rest-http,control-center-agent
        - name: CONFIG_URI
          value: file:///ignite/config/ignite-config.xml
        - name: IGNITE_NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: IGNITE_OVERRIDE_CONSISTENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: GRIDGAIN_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: ignite-credentials
              key: serverusername
        - name: GRIDGAIN_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ignite-credentials
              key: serverpassword
        - name: GRIDGAIN_CLIENT_USERNAME
          valueFrom:
            secretKeyRef:
              name: ignite-credentials
              key: clientusername
        - name: GRIDGAIN_CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ignite-credentials
              key: clientpassword
        ports:
        - containerPort: 10800 # JDBC port
        - containerPort: 11211 # REST port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        volumeMounts:
        - mountPath: /ignite/config
          name: ignite-config
        - mountPath: /ignite/work
          name: ignite-work
        - mountPath: /ignite/storage
          name: ignite-storage
        - mountPath: /ignite/wal
          name: ignite-wal
        - mountPath: /ignite/walarchive
          name: ignite-walarchive
        - mountPath: /ignite/licence
          name: ignite-licence
        - mountPath: /ignite/snapshots
          name: ignite-snapshots
        livenessProbe:
          httpGet:
            path: /ignite?cmd=version
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ignite?cmd=probe
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: ignite-work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 512Mi
        selector:
          matchLabels:
            app: ignite
    - metadata:
        name: ignite-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        selector:
          matchLabels:
            app: ignite
    - metadata:
        name: ignite-wal
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        selector:
          matchLabels:
            app: ignite
    - metadata:
        name: ignite-walarchive
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi
        selector:
          matchLabels:
            app: ignite
    - metadata:
        name: ignite-snapshots
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        selector:
          matchLabels:
            app: ignite
