apiVersion: v1
kind: Service
metadata:
  name: ignite
spec:
  type: LoadBalancer
  ports:
    - port: 11211 
      name: tcp-control
    - port: 10800
      name: tcp-thinclient
      targetPort: 10800
    - port: 47100
      name: tcp-communication
    - port: 47500
      name: tcp-discovery
  selector:
    app: ignite
    type: server
