apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ignite
resources:
  - ignite-namespace.yaml
  - ignite-service.yaml
  - ignite-service-headless.yaml
  - ignite-serviceaccount.yaml
  - ignite-config.yaml
  - ignite-credentials.yaml
  - ignite-statefulset.yaml
#   - ignite-client.yaml

# Uncomment to enable Istio
components:
  - ./istio-mtls

patches:
  - target:
      kind: Namespace
      name: ignite
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ignite
        labels:
          istio-injection: enabled
  - target:
      kind: StatefulSet
      name: ignite
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: ignite
      spec:
        template:
          metadata:
            annotations:
              proxy.istio.io/config: |
                holdApplicationUntilProxyStarts: true
          
# Uncomment to enable LinkerD
#   - target:
#       kind: StatefulSet
#       name: ignite
#     patch: |-
#       apiVersion: apps/v1
#       kind: StatefulSet
#       metadata:
#         name: ignite
#       spec:
#         template:
#           metadata:
#             annotations:
#               linkerd.io/inject: enabled
#               config.linkerd.io/opaque-ports: "10800,47100,47500"
#   - target:
#       kind: Deployment
#       name: ignite-client
#     patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: ignite-client
#       spec:
#         template:
#           metadata:
#             annotations:
#               linkerd.io/inject: enabled
#               config.linkerd.io/opaque-ports: "10800"
